### ISSUE TITLE
FrameLess issue with gnome3

### ISSUE THREAD

**Issue by raphaelvalentin** [eNkru/electron-outlook#2]
Dear, 
Very useful app ! However, I am meeting an issue with Ubuntu 16.04 Gnome3. Due to the actual config `frame:false`, I am disabled to move the window over my desktop. Actually, I solved the issue with a small FIX at:

```
class MailWindowController {
    constructor() {
        this.init()
    }

    init() {
        // Create the browser window.
        this.win = new BrowserWindow({
            x: 100,
            y: 100,
            width: 1400,
            height: 900,
            frame: true, // false per default
            autoHideMenuBar: true
        })
```

Is it possible to have an argument at run like `electron-outlook --withframe `?
Thanks for your support, 
Raphael.

**Comment by eNkru** [comment]
The window can be dragged by the header on the very top of the window.

However, I'll consider to add an option to make the frame available :)

**Comment by eNkru** [comment]
@raphaelvalentin an option is added into the tray right click menu to toggle the window frame

https://github.com/eNkru/electron-outlook/pull/6
