### ISSUE TITLE
Is there an OSX version?

### ISSUE THREAD

**Issue by vigneshmarthandan** [eNkru/electron-outlook#3]
Is there an OSX version?

**Comment by eNkru** [comment]
yup. It's electron app, can be build on any operation system. I am using it on my macbook pro at home.

If you have the development environment, just run the build command in the readme will create your macos version installers.

let me know if you can't build it and need my help :)

**Comment by vigneshmarthandan** [comment]
Thanks for your response. I was able to build and run the app.

**Comment by eNkru** [comment]
thanks to support :+1:
