### ISSUE TITLE
After close and reopen credentials needs to be set over again

### ISSUE THREAD

**Issue by julian-alarcon** [eNkru/electron-outlook#9]
Credentials are always promt after closing the app and opening it.

**Comment by eNkru** [comment]
@julian-alarcon the new electron version disable this feature for a security reason. I downgrade the electron to 3.0.6 to bring it back. 

If you can control your desktop / laptop, feel free to use this feature. Otherwise, It might open a thread to allow other people get your credentials once they have fully access your OS.

**Comment by eNkru** [comment]
will investigate the new way to save login credentials when get some time to spend :)

**Comment by julian-alarcon** [comment]
Hi, I guess that this is my fault, there was no need to change the code.
https://github.com/eNkru/electron-outlook/commit/a22cdbb9691a34a4d1026a459e83e976de963d2e

Your initial setup was most restrictive and specific about the version, `~3.0.6`
The symbol ~ specify that version used will only change the last digit, 3.0.X
The symbol ^ specify that version used can be updated to next not breaking, 3.X.Y

As there is no version 3.1.X of electron, ~3.0.6 and ^3.0.6 will use the same version, the current version as today, 3.0.11.
If in the file yarn.lock and the folder node_modules is specified an older version I guess these will be used by yarn, no matter if you define another version, unless that you run yarn (but I'm guessing here)

https://bytearcher.com/articles/semver-explained-why-theres-a-caret-in-my-package-json/

I found an issue working with the beta version of electron, version 4.0.0-beta.7 and 4.0.0-beta.8. Not saving the session, but as this is a beta so the issue can be ignored for now. As I am using snap packaging data folders are in $HOME/snap/Name_of_app not in $HOME/.config. Maybe I have wrong/old files, that's why my confusion.

This electron app of MS Teams has no issue with the session on electron 3 and 4, just if you want to see what is he making it to work: https://github.com/IsmaelMartinez/teams-for-linux

**Comment by eNkru** [comment]
Thanks for the feedback. I'll take a look see if this app can migrate to Elelctron V4 Beta :)
